# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: OFFLINE.indirect::lang.redirect.category

# Model Form Field configuration
form: $/offline/indirect/models/category/fields.yaml

# Model Class name
modelClass: OFFLINE\Indirect\Models\Category

# Default redirect location
defaultRedirect: offline/indirect/categories

# Create page
create:
    title: OFFLINE.indirect::lang.title.create_category
    redirect: offline/indirect/categories/update/:id
    redirectClose: offline/indirect/categories

# Update page
update:
    title: OFFLINE.indirect::lang.title.edit_category
    redirect: offline/indirect/categories
    redirectClose: offline/indirect/categories
