# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: offline.indirect::lang.redirect.reorder_redirects

# Attribute name
nameFrom: from_url

# Model Class name
modelClass: OFFLINE\Indirect\Models\Redirect

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
