# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: OFFLINE.indirect::lang.title.import
    modelClass: OFFLINE\Indirect\Models\RedirectImport
    list: $/offline/indirect/models/redirectimport/columns.yaml
    redirect: offline/indirect/redirects
export:
    title: OFFLINE.indirect::lang.title.export
    modelClass: OFFLINE\Indirect\Models\RedirectExport
    list: $/offline/indirect/models/redirectexport/columns.yaml
    redirect: offline/indirect/redirects
    filename: redirects.csv