# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: adrenth.redirect::lang.redirect.redirect

# Model Form Field configuration
form: $/adrenth/redirect/models/redirect/fields.yaml

# Model Class name
modelClass: Adrenth\Redirect\Models\Redirect

# Default redirect location
defaultRedirect: adrenth/redirect/redirects

# Create page
create:
    title: adrenth.redirect::lang.title.create_redirect
    redirect: adrenth/redirect/redirects/update/:id
    redirectClose: adrenth/redirect/redirects

# Update page
update:
    title: adrenth.redirect::lang.title.edit_redirect
    redirect: adrenth/redirect/redirects
    redirectClose: adrenth/redirect/redirects