# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: OFFLINE.indirect::lang.redirect.redirect

# Model Form Field configuration
form: $/offline/indirect/models/redirect/fields.yaml

# Model Class name
modelClass: OFFLINE\Indirect\Models\Redirect

# Default redirect location
defaultRedirect: offline/indirect/redirects

# Create page
create:
    title: OFFLINE.indirect::lang.title.create_redirect
    redirect: offline/indirect/redirects/update/:id
    redirectClose: offline/indirect/redirects

# Update page
update:
    title: OFFLINE.indirect::lang.title.edit_redirect
    redirect: offline/indirect/redirects
    redirectClose: offline/indirect/redirects